require("which-key").setup {
  icons = {
    breadcrumb = "»",
    separator = "➜",
    group = "",
  },
  layout = {
    height = {
      min = 4,
      max = 10
    },
  },
}
require("which-key").register({
  ["\\p"]   = { name = "Preview+" },
  ["\\pc"]  = { name = "Colorizer" },
  ["\\pg"]  = { name = "Markdown" },
  ["\\s"]   = { name = "Search+" },
  ["\\ss"]  = { name = "Telescope" },
  ["\\si"]  = { name = "Search Function" },
  ["\\sf"]  = { name = "Search File" },
  ["\\sg"]  = { name = "Search Grep" },
  ["\\sb"]  = { name = "Search Buffer" },
  ["\\sh"]  = { name = "Search Help" },
  ["\\so"]  = { name = "Search oldfile" },
  ["\\l"]   = { name = "lsp+"},
  ["\\ls"]  = { name = "SymbolsOutline"},
  ["\\lt"]  = { name = "Trouble"},
  ["\\d"]   = { name = "Debug+"},
  ["\\ds"]  = { name = "Continue"},
  ["\\dp"]  = { name = "Stop"},
  ["\\dr"]  = { name = "Restart"},
  ["\\db"]  = { name = "Breakpoint"},
  ["\\dt"]  = { name = "Run To Cursor"},
  ["\\dq"]  = { name = "Over"},
  ["\\di"]  = { name = "Step Into"},
  ["\\do"]  = { name = "Step Out"},
  ["\\dw"]  = { name = "ChooseWin"},
  ["\\t"]   = { name = "TreeSitter+"},
  ["\\tr"]  = { name = "Smart Rename"},
  ["\\t="]  = { name = "Indent File"},
  ["\\u"]   = { name = "UI+"},
  ["\\um"]  = { name = "Menu(not working)"},
  ["\\uc"]  = { name = "Clock"},
  ["<Space>f"]   = { name = "Functions+"},
  ["<Space>fs"]  = { name = "Space+"},
  ["<Space>fsd"] = { name = "Delete"},
  ["<Space>b"]   = { name = "Buffer+"},
  ["<Space>bb"]  = { name = "Goto"},
  ["<Space>bd"]  = { name = "Delete"},
  ["<Space>bn"]  = { name = "Next"},
  ["<Space>bp"]  = { name = "Previous"},
  ["<Space>bs"]  = { name = "Buffers"},
  ["<Space>t"]   = { name = "Tab+"},
  ["<Space>te"]  = { name = "New"},
  ["<Space>tt"]  = { name = "Goto"},
  ["<Space>tq"]  = { name = "Close"},
  ["<Space>to"]  = { name = "Close Others"},
  ["<Space>tn"]  = { name = "Next"},
  ["<Space>tp"]  = { name = "Previous"},
  ["<Space>w"]   = { name = "Windows+"},
  ["<Space>ws"]  = { name = "Split Vertically"},
  ["<Space>wv"]  = { name = "Split"},
  ["<Space>ww"]  = { name = "Switch"},
  ["<Space>wx"]  = { name = "Swap Cur Next"},
  ["<Space>wT"]  = { name = "Cur Into NewTab"},
  ["<Space>wq"]  = { name = "Quit"},
  ["<Space>wh"]  = { name = "Go Left"},
  ["<Space>wj"]  = { name = "Go Down"},
  ["<Space>wk"]  = { name = "Go Up"},
  ["<Space>wl"]  = { name = "Go Right"},
  ["<Space>w|"]  = { name = "Width Max"},
  ["<Space>w="]  = { name = "Eq Height Width"},
  ["<Space>we"]  = { name = "Explore"},
  ["v"]  = { name = "Visual+"},
  ["vv"] = { name = "Visual Mode"},
  ["vb"] = { name = "Visual Block"},
  ["<C-w>"]   = { name = "Windows+"},
  ["g"] = { name = "" },
  ["<Leader>w"] = { name = "Choose Windows" },
})
